In [4]:
# Lab 7 Learning rate and Evaluation
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [5]:
# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
# 실행시에 데이터를 제공하는 방법으로 실제 딥러닝 모델 구축시 많이 쓰인다.
# sess.run 에서 feed_dict에 dictionary 형식으로 값을 넣어주면 되고 이를 feeding이라 한다.

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

In [6]:
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# axis = 1은 가로축을 의미하고 reduce_mean은 평균을 의미한다. 즉 가로축들의 평균

# Try to change learning_rate to small numbers
optimizer = tf.train.GradientDescentOptimizer(
    learning_rate=0.01).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
# argmax 제일 큰값 , axis = 1

is_correct = tf.equal(prediction, tf.argmax(Y, 1))
#prediction과 tf.argmax값을 비교해서 true or false출력 

accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
# 텐서를 새로운 형태로 캐스팅하는데 사용한다.

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
# tf.global_variables_initializer()는 모델의 모든 변수를 초기화합니다.

    for step in range(100):
        cost_val, W_val, _ = sess.run(
            [cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

#learning late = 0.01

0 5.191887 [[-2.1120422   1.169702    1.4720718 ]
 [-0.60706806 -0.3920611   0.45690614]
 [ 0.5427132   1.4547732  -2.348614  ]]
1 4.9824057 [[-2.109618    1.1636082   1.4757415 ]
 [-0.59099734 -0.41796705  0.46674135]
 [ 0.55884725  1.4299737  -2.3399487 ]]
2 4.773663 [[-2.107208    1.1575382   1.4794015 ]
 [-0.5749644  -0.44381475  0.47655615]
 [ 0.574953    1.4052132  -2.3312938 ]]
3 4.565818 [[-2.1048152   1.151496    1.4830507 ]
 [-0.55897945 -0.4695919   0.48634833]
 [ 0.5910217   1.3805016  -2.322651  ]]
4 4.359077 [[-2.1024435   1.145487    1.4866881 ]
 [-0.5430563  -0.49528217  0.4961155 ]
 [ 0.60704124  1.3558524  -2.314021  ]]
5 4.153717 [[-2.1000981   1.1395172   1.4903126 ]
 [-0.5272144  -0.5208637   0.50585514]
 [ 0.6229942   1.3312842  -2.3054059 ]]
6 3.9501143 [[-2.097786    1.1335946   1.4939228 ]
 [-0.51148134 -0.5463062   0.51556456]
 [ 0.6388556   1.3068236  -2.2968066 ]]
7 3.7487912 [[-2.095516    1.1277299   1.4975176 ]
 [-0.49589708 -0.5715669   0.525241  ]
 [ 0.

In [7]:
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# axis = 1은 가로축을 의미하고 reduce_mean은 평균을 의미한다. 즉 가로축들의 평균

# Try to change learning_rate to small numbers
optimizer = tf.train.GradientDescentOptimizer(
    learning_rate=0.1).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
# argmax 제일 큰값 , axis = 1

is_correct = tf.equal(prediction, tf.argmax(Y, 1))
#prediction과 tf.argmax값을 비교해서 true or false출력 

accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
# 텐서를 새로운 형태로 캐스팅하는데 사용한다.

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
# tf.global_variables_initializer()는 모델의 모든 변수를 초기화합니다.

    for step in range(100):
        cost_val, W_val, _ = sess.run(
            [cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

#learning late = 0.1

0 5.191887 [[-2.0901198   1.1146725   1.5051788 ]
 [-0.46215943 -0.6256517   0.5455881 ]
 [ 0.6881166   1.231295   -2.2705393 ]]
1 3.1364584 [[-2.0698724   1.0590404   1.5405635 ]
 [-0.31644705 -0.8669065   0.6411305 ]
 [ 0.8364465   0.99780715 -2.1853814 ]]
2 2.0724528 [[-2.0986466   1.0547832   1.5735948 ]
 [-0.43205884 -0.8415371   0.7313729 ]
 [ 0.73653996  1.0154992  -2.1031668 ]]
3 1.8180536 [[-2.1017838   1.0267644   1.6047506 ]
 [-0.41325656 -0.9459239   0.8169575 ]
 [ 0.76648754  0.90607977 -2.023695  ]]
4 1.5991962 [[-2.128746    1.0257697   1.6327076 ]
 [-0.52414143 -0.91210186  0.8940203 ]
 [ 0.6682486   0.93005514 -1.9494314 ]]
5 1.4104228 [[-2.1292915   1.0017395   1.6572833 ]
 [-0.4947812  -1.0059249   0.95848316]
 [ 0.7055218   0.82695067 -1.8836001 ]]
6 1.2804351 [[-2.1515565   1.004175    1.6771127 ]
 [-0.58366317 -0.9626085   1.0040487 ]
 [ 0.62253225  0.8570642  -1.8307241 ]]
7 1.2053932 [[-2.149767    0.9875567   1.6919413 ]
 [-0.54185116 -1.0222003   1.0218285 ]
 